<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="GK" failures="1" tests="12" name="Default test" time="36.872" errors="0" timestamp="2025-06-11T15:44:57 IST">
  <testcase classname="tests.FormTests" name="testFormElementsPresence" time="0.858"/>
  <testcase classname="tests.FormTests" name="testSuccessfulFormSubmission" time="2.431"/>
  <testcase classname="tests.FormTests" name="testRequiredFieldValidation" time="0.511">
    <failure type="java.lang.AssertionError" message="First name field should have error class expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: First name field should have error class expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.FormTests.testRequiredFieldValidation(FormTests.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testRequiredFieldValidation -->
  <testcase classname="tests.FormTests" name="testEmailValidation" time="1.175"/>
  <testcase classname="tests.FormTests" name="testRadioButtonFunctionality" time="0.547"/>
  <testcase classname="tests.FormTests" name="testCheckboxFunctionality" time="1.4"/>
  <testcase classname="tests.FormTests" name="testDropdownFunctionality" time="2.012"/>
  <testcase classname="tests.FormTests" name="testFormResetFunctionality" time="1.874"/>
  <testcase classname="tests.FormTests" name="testAgeFieldValidation" time="0.935"/>
  <testcase classname="tests.FormTests" name="testTextareaFunctionality" time="0.486"/>
  <testcase classname="tests.FormTests" name="testCompleteUserJourney" time="2.454"/>
  <testcase classname="tests.FormTests" name="testFormWithPartialData" time="1.636"/>
</testsuite> <!-- Default test -->
